<option value="Ajuste">Ajuste</option>
<option value="Autorizacion">Autorizacion</option>
<option value="Conversacion">Conversacion</option>
<option value="Dispositivo">Dispositivo</option>
<option value="Empleado">Empleado</option>
<option value="Empresa">Empresa</option>
<option value="Feriado">Feriado</option>
<option value="Horario">Horario</option>
<option value="HorarioRotativo">Horario Rotativo</option>
<option value="HorarioSemanal">Horario Semanal</option>
<option value="Licencia">Licencia</option>
<option value="Mensaje">Mensaje</option>
<option value="Menu">Menu</option>
<option value="Modulo">Modulo</option>
<option value="Oficina">Oficina</option>
<option value="Perfil">Perfil</option>
<option value="Permiso">Permiso</option>
<option value="Registro">Registro</option>
<option value="Sucursal">Sucursal</option>
<option value="TipoEmpleado">Tipo Empleado</option>
<option value="TipoHorario">Tipo Horario</option>
<option value="TipoLicencia">Tipo Licencia</option>
<option value="Trabaja">Trabaja</option>
<option value="Turno">Turno</option>
